<a href="https://colab.research.google.com/github/jagvgithub/Python_para_IA/blob/main/01MIAR_Exam_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Examen Primera Convocatoria

In [62]:
import pandas as pd  # Para manipulación de datos tabulares
import numpy as np   # Para operaciones numéricas eficientes
from datetime import datetime  # Para trabajar con fechas y horas
import warnings  # Para manejar advertencias
import plotly.express as px  # Para gráficos interactivos y de alta calidad
import seaborn as sns  # Para gráficos estadísticos atractivos
import matplotlib.pyplot as plt  # Para trazado básico y personalizado
warnings.filterwarnings("ignore")  # Ignorar advertencias

## 01 - 1.25pt
- Crear un array de NumPy de dimensiones 5x5, con números enteros aleatorios en el rango [-40, 40]
- Hacer los siguientes reemplazos en orden
    - Reemplazar todos los valores multiplos de 3 por 1
    - Reemplazar todos los valores pares positivos por 0
    - Reemplazar todos los valores pares negativos por Nan
- Averiguar cuantos elementos tienen Nan por fila

In [14]:

p1 = np.random.randint(-40,40,size=(5,5))


''' Reemplazar todos los valores multiplos de 3 por 1 '''
p1[p1%3==0]=1
print(p1)

''' Reemplazar todos los valores pares positivos por 0 '''

p1_2 =np.where(((p1%2==0) & (p1 > 0)) ,0,p1)

''' Reemplazar todos los valores pares negativos por Nan '''
p1_2 =np.where(((p1%2==0) & (p1 < 0)),np.nan,p1_2)
print(p1_2)


[[ 13 -19 -40  20  -2]
 [  2  32  14   1 -31]
 [ 29 -23  32 -25   1]
 [-20 -20  28  25 -14]
 [-16   1   1   1   1]]
[[ 13. -19.  nan   0.  nan]
 [  0.   0.   0.   1. -31.]
 [ 29. -23.   0. -25.   1.]
 [ nan  nan   0.  25.  nan]
 [ nan   1.   1.   1.   1.]]


## 02 - 1.25pt
- Escribir un generador que genere todos los factores de un número. Un factor es un número natural que puede dividir exactamente a otro número.

In [ ]:
number = 1000
expected_factors = [1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 125, 200, 250, 500, 1000]
gen = factor_generator(number) # This calls tour function factor_generator
output = [next(gen) for n in range(len(expected_factors))]
assert(expected_factors == output)  # This will fail if the element is not found correctly

In [ ]:
# Your solution HERE !!!!

## 03 - 1.25pt
- Escribir una función que reciba un Dataframe, en la columna "name" convierta el primer carácter de cada nombre a mayúsculas.

In [ ]:
dataframe = pd.DataFrame({
    'name': ['tamayo','tanjiro','inosuke', 'zenitsu', 'nezuko'],
    'date_of_birth ': ['13/01/2002','18/03/1999','21/11/1998','10/10/2002','05/04/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

expected_dataframe = pd.DataFrame({
    'name': ['Tamayo', 'Tanjiro', 'Inosuke', 'Zenitsu', 'Nezuko'],
    'date_of_birth ': ['13/01/2002','18/03/1999','21/11/1998','10/10/2002','05/04/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

output = capitalize_name(dataframe) # This calls your function capitalize_name
assert(expected_dataframe.equals(output)) # This will fail if result is not as expected

In [33]:
df = pd.DataFrame({
    'name': ['Tamayo', 'tanjiro', 'Inosuke', 'zenitsu', 'nezuko'],
    'date_of_birth ': ['13/01/2002','18/03/1999','21/11/1998','10/10/2002','05/04/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

def capitalizar(df):
  print(df)
  df['name'] = df['name'].str[0].str.upper() + df['name'].str[1:-1]
  return print(df)


''' Aplicacion '''

capitalizar(df)

      name date_of_birth    age
0   Tamayo     13/01/2002  18.5
1  tanjiro     18/03/1999  21.2
2  Inosuke     21/11/1998  22.5
3  zenitsu     10/10/2002  22.0
4   nezuko     05/04/1997  23.0
     name date_of_birth    age
0   Tamay     13/01/2002  18.5
1  Tanjir     18/03/1999  21.2
2  Inosuk     21/11/1998  22.5
3  Zenits     10/10/2002  22.0
4   Nezuk     05/04/1997  23.0


## 04 - 1.25pt
- 200 personas hacen una review de una película, dándole una puntuación de 0.0 a 5.0 a dicha película
- Crear una lista aleatoria con las posibles puntuaciones, es decir, 200 puntuaciones entre 0.0 y 5.0
- Discretizar dichas puntuaciones en 4 categorias [muy mala, mala, buena, excelente], los límites de cada categoría son a libre elección
- Discretizar dichas puntuaciones en 5 categorías distribuidas con rangos homogéneos (similar cantidad de valores en cada categoría)
- Mostrar las categorías creadas y cuantos elementos hay en cada una de ellas

In [40]:
df = pd.DataFrame({'numero': np.random.randint(0, 5, 200)})
df['bins'] = pd.cut(x=df['numero'], bins=4,
                    labels=['muy mala', 'mala', 'buena',
                            'excelente'])

df['categoria'] = np.where(df['numero']<=1,"1",
                           np.where(df['numero']<=2,"2",
                            np.where(df['numero']<=3,"3",
                              np.where(df['numero']<=4,"4","5"))))

print(df)

df['categoria'].value_counts()

     numero       bins categoria
0         2       mala         2
1         0   muy mala         1
2         0   muy mala         1
3         4  excelente         4
4         2       mala         2
..      ...        ...       ...
195       4  excelente         4
196       4  excelente         4
197       0   muy mala         1
198       2       mala         2
199       3      buena         3

[200 rows x 3 columns]


categoria
1    67
3    52
4    46
2    35
Name: count, dtype: int64

## 05 - 5pt

El conjunto de datos "estaciones_bici.csv" (fichero disponible adjunto a la actividad) proviene de una descarga de datos del servicio web de la empresa municipal Valenbici, dedicada al alquiler de bicicletas en Valencia.

Los datos recabados de este servicio web son de mediciones cada 10 minutos de las estaciones:

https://valencia.opendatasoft.com/explore/dataset/valenbisi-disponibilitat-valenbisi-dsiponibilidad/information/

Cada estación está compuesta por un número variable de bornetas (total) donde se pueden anclar las bicicletas. Los datos obtenidos de cada estación (registros) refleja el número de bornetas libres (free) y el número de bicicletas disponibles (available).

#### Columnas para trabajar:
- station: id de la estación
- total: número total de bornetas
- updated: timestamp del estado en de bicis en la estación
- available: número de bicis disponibles

#### Preguntas
1. Carga de datos de csv (estaciones_bici.csv) en un DataFrame
2. ¿Cuál es el rango temporal del dataset? Obtención del número de estaciones que tienen un total de 30 bornetas
3. Número de estación con la media más alta de bicis disponibles
4. Realizar el histograma de bicis disponibles de la estación del punto anterior
5. Realizar gráfica con  la línea temporal de bicis disponibles de la estación del punto anterior. Pista, es necesario cambiar el índice a uno tipo fecha

In [74]:
from google.colab import files
uploaded = files.upload()
file_path = list(uploaded.keys())[0]
df = pd.read_csv(file_path,sep=';')

display(df.head())

Saving estaciones_bici.csv to estaciones_bici (4).csv


Unnamed: 0                       _id  available  connected  \
0           0  5c6050a42554172704fccdc0          9          1   
1           1  5c6050a42554172704fccdc1          6          1   
2           2  5c605be225541729b7d50885         20          1   
3           3  5c605be225541729b7d50886          6          1   
4           4  5c605be225541729b7d50887          9          1   

             download_date  station  free  open  ticket  total  \
0  2019-02-10 17:25:37.787       64    11     1       0     20   
1  2019-02-10 17:25:37.787       73    14     1       1     20   
2  2019-02-10 18:13:39.827       63     0     1       1     20   
3  2019-02-10 18:13:39.827       64    14     1       0     20   
4  2019-02-10 18:13:39.827       65    10     1       1     19   

                   updated  
0  2019-02-10 17:21:13.000  
1  2019-02-10 17:24:13.000  
2  2019-02-10 18:09:16.000  
3  2019-02-10 18:12:15.000  
4  2019-02-10 18:09:16.000

In [75]:
df['download_date'] = df['download_date'].str[0:9]

df['download_date'] = pd.to_datetime(df['download_date'], format='%Y-%m-%d')

li_fecha,ls_fecha = df['updated'].min(),df['updated'].max()
print(f"\n El rango de fechas contemplado en el cojunto de datos va desde {li_fecha} hasta {ls_fecha}  ")


 El rango de fechas contemplado en el cojunto de datos va desde 2019-02-10 17:21:13.000 hasta 2019-02-11 23:42:16.000  


In [76]:
# Eliminar filas con valores nulos en la columna 'co'
datos_sin_nulos = df.dropna(subset=['station'])

# Calcular la media de ingreso para cada objectid
ingreso_por_objectid = datos_sin_nulos.groupby('station')['free'].mean().reset_index()

# Crear el gráfico de barras
fig = px.bar(ingreso_por_objectid, x='station', y='free', title='media más alta de bicis disponibles')

# Ajustes estéticos
fig.update_layout(xaxis_title='station', yaxis_title='media más alta de bicis disponibles', xaxis_tickangle=-45)

# Mostrar el gráfico
fig.show()

max_media_co = ingreso_por_objectid['free'].max()
estacion_max_media = ingreso_por_objectid.loc[ingreso_por_objectid['free'] == max_media_co, 'station'].iloc[0]

print(f'\n El número de estación con la media más alta de bicis disponibles fue: {estacion_max_media}')


 El número de estación con la media más alta de bicis disponibles fue: 194


In [77]:
valores_histograma = list(df[df['station']== str(estacion_max_media)]['free'])

# Convertir la lista de datos en un DataFrame de pandas
df = pd.DataFrame(valores_histograma, columns=['valor'])

# Crear el histograma con Plotly
fig = px.histogram(df, x='valor', nbins=df['valor'].nunique(), title=f'histograma de dióxido de nitrógeno de la estación {estacion_max_media}')
fig.update_xaxes(title='Estación')
fig.update_yaxes(title='Frecuencia')

# Mostrar el histograma
fig.show()

In [79]:
filtro = valores_histograma = df[df['station'] == str(estacion_max_media)][['download_date', 'free']]

# Convertir la columna de fecha_carga a tipo datetime si aún no está en ese formato
filtro['download_date'] = pd.to_datetime(filtro['download_date'])

# Establecer la columna de fecha_carga como el índice del DataFrame
filtro.set_index('download_date', inplace=True)

# Configurar el estilo de seaborn
sns.set_style("whitegrid")

# Graficar la serie de tiempo
plt.figure(figsize=(12, 6))
sns.lineplot(data=filtro, x=filtro.index, y='o3', color='skyblue', linewidth=2, markers='o', markerfacecolor='blue', markeredgewidth=0)

# Anotar los valores en cada punto
for index, row in filtro.iterrows():
    plt.annotate(f'{int(row["o3"])}', xy=(index, row["o3"]), xytext=(-10, 5), textcoords='offset points', fontsize=9)

plt.title('Serie de tiempo de bicis', fontsize=16)
plt.xlabel('Fecha', fontsize=14)
plt.ylabel('Valor de bicis', fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()

KeyError: 'station'